
skillMetadata:
  sections:
    - name: Connection
      fields:
        - type: label
          label: Websocket Connection
        - name: websocket_ip
          type: text
          label: IP
          value: ""
        - name: websocket_port
          type: text
          label: Port
          value: ""
